// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dynamic_table_variables.sql

package sqlcrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDynamicField = `-- name: CreateDynamicField :one
INSERT INTO dynamic_table_variables (
  id, name, variable_type, dynamic_table_id,  created_at, created_by, modified_at, modified_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateDynamicFieldParams struct {
	ID             string
	Name           string
	VariableType   string
	DynamicTableID string
	CreatedAt      pgtype.Timestamp
	CreatedBy      string
	ModifiedAt     pgtype.Timestamp
	ModifiedBy     string
}

func (q *Queries) CreateDynamicField(ctx context.Context, arg CreateDynamicFieldParams) (string, error) {
	row := q.db.QueryRow(ctx, createDynamicField,
		arg.ID,
		arg.Name,
		arg.VariableType,
		arg.DynamicTableID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteDynamicFields = `-- name: DeleteDynamicFields :exec
DELETE
FROM dynamic_table_variables
WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteDynamicFields(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteDynamicFields, dollar_1)
	return err
}

const fetchDynamicFields = `-- name: FetchDynamicFields :many
SELECT dynamic_table_variables.id, dynamic_table_variables.name, dynamic_table_variables.variable_type, dynamic_table_variables.dynamic_table_id, dynamic_table_variables.created_at, dynamic_table_variables.modified_at, dynamic_table_variables.created_by, dynamic_table_variables.modified_by,dynamic_tables.table_name as dynamic_table_name
FROM dynamic_table_variables
JOIN dynamic_tables
ON dynamic_tables.id = dynamic_table_variables.dynamic_table_id
WHERE dynamic_table_variables.id = ANY($1::text[])
ORDER BY dynamic_table_variables.id
`

type FetchDynamicFieldsRow struct {
	ID               string
	Name             string
	VariableType     string
	DynamicTableID   string
	CreatedAt        pgtype.Timestamp
	ModifiedAt       pgtype.Timestamp
	CreatedBy        string
	ModifiedBy       string
	DynamicTableName string
}

func (q *Queries) FetchDynamicFields(ctx context.Context, dollar_1 []string) ([]FetchDynamicFieldsRow, error) {
	rows, err := q.db.Query(ctx, fetchDynamicFields, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchDynamicFieldsRow
	for rows.Next() {
		var i FetchDynamicFieldsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariableType,
			&i.DynamicTableID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.DynamicTableName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchDynamicFieldsByDynamicTable = `-- name: FetchDynamicFieldsByDynamicTable :many
SELECT dynamic_table_variables.id, dynamic_table_variables.name, dynamic_table_variables.variable_type, dynamic_table_variables.dynamic_table_id, dynamic_table_variables.created_at, dynamic_table_variables.modified_at, dynamic_table_variables.created_by, dynamic_table_variables.modified_by,dynamic_tables.table_name as dynamic_table_name
FROM dynamic_table_variables
JOIN dynamic_tables
ON dynamic_tables.id = dynamic_table_variables.dynamic_table_id
WHERE dynamic_tables.id = $1
ORDER BY dynamic_table_variables.id
`

type FetchDynamicFieldsByDynamicTableRow struct {
	ID               string
	Name             string
	VariableType     string
	DynamicTableID   string
	CreatedAt        pgtype.Timestamp
	ModifiedAt       pgtype.Timestamp
	CreatedBy        string
	ModifiedBy       string
	DynamicTableName string
}

func (q *Queries) FetchDynamicFieldsByDynamicTable(ctx context.Context, id string) ([]FetchDynamicFieldsByDynamicTableRow, error) {
	rows, err := q.db.Query(ctx, fetchDynamicFieldsByDynamicTable, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchDynamicFieldsByDynamicTableRow
	for rows.Next() {
		var i FetchDynamicFieldsByDynamicTableRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariableType,
			&i.DynamicTableID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.DynamicTableName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchDynamicFieldsByDynamicTableName = `-- name: FetchDynamicFieldsByDynamicTableName :many
SELECT dynamic_table_variables.id, dynamic_table_variables.name, dynamic_table_variables.variable_type, dynamic_table_variables.dynamic_table_id, dynamic_table_variables.created_at, dynamic_table_variables.modified_at, dynamic_table_variables.created_by, dynamic_table_variables.modified_by,dynamic_tables.table_name as dynamic_table_name
FROM dynamic_table_variables
JOIN dynamic_tables
ON dynamic_tables.id = dynamic_table_variables.dynamic_table_id
WHERE dynamic_tables.table_name = $1
ORDER BY dynamic_table_variables.id
`

type FetchDynamicFieldsByDynamicTableNameRow struct {
	ID               string
	Name             string
	VariableType     string
	DynamicTableID   string
	CreatedAt        pgtype.Timestamp
	ModifiedAt       pgtype.Timestamp
	CreatedBy        string
	ModifiedBy       string
	DynamicTableName string
}

func (q *Queries) FetchDynamicFieldsByDynamicTableName(ctx context.Context, tableName string) ([]FetchDynamicFieldsByDynamicTableNameRow, error) {
	rows, err := q.db.Query(ctx, fetchDynamicFieldsByDynamicTableName, tableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchDynamicFieldsByDynamicTableNameRow
	for rows.Next() {
		var i FetchDynamicFieldsByDynamicTableNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariableType,
			&i.DynamicTableID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.DynamicTableName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
