// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Token struct {
	ID        string
	Value     string
	Active    int32
	Expires   pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	CreatedBy string
	UpdatedAt pgtype.Timestamp
	UpdatedBy string
	UserID    string
}

type User struct {
	ID        string
	Username  string
	Password  pgtype.Text
	Active    int32
	CreatedAt pgtype.Timestamp
	CreatedBy string
	UpdatedAt pgtype.Timestamp
	UpdatedBy string
}
