// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_children.sql

package sqlcrepo

import (
	"context"
)

const deleteWorkflowChildren = `-- name: DeleteWorkflowChildren :exec
DELETE from workflows_children
where workflows_children.workflow_id = $1
`

func (q *Queries) DeleteWorkflowChildren(ctx context.Context, workflowID string) error {
	_, err := q.db.Exec(ctx, deleteWorkflowChildren, workflowID)
	return err
}

const saveWorkflowChildren = `-- name: SaveWorkflowChildren :exec
INSERT INTO workflows_children (
  workflow_id, children_id
) VALUES (
  $1, $2
)
`

type SaveWorkflowChildrenParams struct {
	WorkflowID string
	ChildrenID string
}

func (q *Queries) SaveWorkflowChildren(ctx context.Context, arg SaveWorkflowChildrenParams) error {
	_, err := q.db.Exec(ctx, saveWorkflowChildren, arg.WorkflowID, arg.ChildrenID)
	return err
}
